### ISSUE TITLE
LoadBalancer object not hashable

### ISSUE THREAD

**Issue by laerlingSAP** [sapcc/octavia-f5-provider-driver#53]
Found at revision: 05bae2a4cbb5f00a61aec5c7ad036e35a59a451a

Steps to reproduce:
1. Clear Octavia database
2. Start Octavia API and octavia-f5-provider-driver
3. Create a load balancer via the API

Expected behavior:
Load balancer is created without errors

Observed behavior:
Exception at `octavia_f5/controller/worker/controller_worker.py:102`.
Instance of LoadBalancer cannot be added to set due to not being hashable.

Stack trace:
```
[-] Failed to call immediate 'octavia_f5.controller.worker.controller_worker.ControllerWorker.pending_sync' (it runs every 120.00 seconds): TypeError: unhashable type: 'LoadBalancer'
Traceback (most recent call last):
  File "/home/laerling/.virtualenv/octavia/lib/python3.7/site-packages/futurist/periodics.py", line 290, in run
    work()
  File "/home/laerling/.virtualenv/octavia/lib/python3.7/site-packages/futurist/periodics.py", line 64, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "/home/laerling/.virtualenv/octavia/lib/python3.7/site-packages/futurist/periodics.py", line 178, in decorator
    return f(*args, **kwargs)
  File "/home/laerling/.virtualenv/octavia/lib/python3.7/site-packages/oslo_concurrency/lockutils.py", line 328, in inner
    return f(*args, **kwargs)
  File "/home/laerling/workspace/octavia-f5-provider-driver/octavia_f5/controller/worker/controller_worker.py", line 102, in pending_sync
    lbs.add(lb)
TypeError: unhashable type: 'LoadBalancer'

```

**Comment by laerlingSAP** [comment]
Was fixed with #55
